#if !defined(AFX_AUDIOINPUTPINS_H__05F36229_BB39_4F49_A114_4FFCB4112C6E__INCLUDED_)
#define AFX_AUDIOINPUTPINS_H__05F36229_BB39_4F49_A114_4FFCB4112C6E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAudioInputPins wrapper class

class CAudioInputPins : public COleDispatchDriver
{
public:
	CAudioInputPins() {}		// Calls COleDispatchDriver default constructor
	CAudioInputPins(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAudioInputPins(const CAudioInputPins& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetCount();
	void SetCount(short);

// Operations
public:
	short FindInputPin(LPCTSTR strInputPinName);
	CString FindInputPinName(short index);
	LPDISPATCH GetItem(const VARIANT& Key);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AUDIOINPUTPINS_H__05F36229_BB39_4F49_A114_4FFCB4112C6E__INCLUDED_)
