#if !defined(AFX_AUDIOCOMPRESSORS_H__EC25EE53_CBD2_4888_BA76_8CE913D714B8__INCLUDED_)
#define AFX_AUDIOCOMPRESSORS_H__EC25EE53_CBD2_4888_BA76_8CE913D714B8__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAudioCompressors wrapper class

class CAudioCompressors : public COleDispatchDriver
{
public:
	CAudioCompressors() {}		// Calls COleDispatchDriver default constructor
	CAudioCompressors(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAudioCompressors(const CAudioCompressors& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetCount();
	void SetCount(short);

// Operations
public:
	short FindAudioCompressor(LPCTSTR strName);
	CString FindAudioCompressorName(short index);
	LPDISPATCH GetItem(const VARIANT& Key);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AUDIOCOMPRESSORS_H__EC25EE53_CBD2_4888_BA76_8CE913D714B8__INCLUDED_)
