#if !defined(AFX_AUDIODEVICES_H__041BE867_26E9_4724_AB09_BF1D45EE453A__INCLUDED_)
#define AFX_AUDIODEVICES_H__041BE867_26E9_4724_AB09_BF1D45EE453A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAudioDevices wrapper class

class CAudioDevices : public COleDispatchDriver
{
public:
	CAudioDevices() {}		// Calls COleDispatchDriver default constructor
	CAudioDevices(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAudioDevices(const CAudioDevices& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetCount();
	void SetCount(short);

// Operations
public:
	short FindDevice(LPCTSTR strDeviceName);
	CString FindDeviceName(short index);
	LPDISPATCH GetItem(const VARIANT& Key);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AUDIODEVICES_H__041BE867_26E9_4724_AB09_BF1D45EE453A__INCLUDED_)
