HANDLE    	WINAPI  BitmapToDIB (HBITMAP, HPALETTE);
HBITMAP  	WINAPI  BitmapCreate(WORD, WORD, WORD, HPALETTE);
BOOL      	WINAPI  PaintDIB(HDC, LPRECT,	HANDLE, LPRECT, CPalette* pPal);
WORD      	WINAPI  PaletteSize (LPSTR lpbi);
LPSTR     	WINAPI  FindDIBBits (LPSTR lpbi);
WORD      	WINAPI  DIBNumColors (LPSTR lpbi);
DWORD     	WINAPI  DIBHeight (LPSTR lpDIB);
DWORD     	WINAPI  DIBWidth (LPSTR lpDIB);
BOOL	  	WINAPI 	DDBPaint(HDC, LPRECT, HBITMAP, LPRECT, HPALETTE); 
CBitmap* 	WINAPI 	GetBitmap(LPSTR pStr);
void 		WINAPI 	DrawCBitmap(CDC* pDC, CBitmap* pBMP, CPoint point);
CBitmap*	WINAPI CreateFillingBMP(COLORREF rgbFill, UINT Width, UINT Height);
CBitmap*	WINAPI CreateRectBMP(COLORREF rgbFill, UINT Width, UINT Height);
BOOL		WINAPI CreateDIBPalette(HANDLE hDIB, CPalette* pPal);
CBitmap*	WINAPI LoadFile(CString strFile);
BOOL		WINAPI LoadFromBuffer(BYTE* pBuff, int nSize, IPicture** pPicture);
