//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by eLearningCapture.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ELEARNINGCAPTURE_DIALOG     102
#define ID_BTN_CLOSE                    102
#define ID_BTN_FIRST                    103
#define IDD_CLOSE_TODO                  103
#define ID_BTN_PREV                     104
#define IDD_GOTO_SLIDE                  104
#define ID_BTN_NEXT                     105
#define IDD_VIDEO_EXIST                 105
#define ID_BTN_LAST                     106
#define IDD_SEL_FILE                    106
#define ID_BTN_REC                      107
#define ID_BTN_PAUSE                    108
#define ID_BTN_STOP                     109
#define ID_BTN_VIEW                     110
#define ID_PAGE_NO_EDIT                 111
#define IDS_TITLE                       112
#define ID_BTN_HELP                     113
#define IDS_PREVIEW                     114
#define IDS_COM_INIT_ERR                115
#define IDS_COM_ABORT                   116
#define ID_BTN_DEMO                     116
#define IDS_DEVICE_LIST_ERR             117
#define IDS_DEVICE_CHOOSE_ERR           118
#define IDS_FILE_EXIST                  119
#define IDS_CAPTURE_ERR                 120
#define ID_BTN_PREVIEW                  121
#define IDS_NO_ERR_HANDLER              122
#define IDS_ERR_OCCUR                   123
#define IDS_ERR_CREATE                  124
#define IDS_ACTING                      125
#define ID_BTN_OPEN                     126
#define ID_BTN_CAPTURE                  127
#define IDR_MAINFRAME                   128
#define IDS_PPT_OPEN_VIEWER_ERROR       128
#define ID_BTN_NG                       128
#define IDB_SEP                         129
#define IDS_PPT_FILE                    129
#define ID_TIME_DISPLAY                 130
#define IDS_CREATE_ERROR                131
#define IDS_CAPTURE_PREPARE_ERR         132
#define IDS_COMMON_ERR                  132
#define IDB_NEXT                        133
#define IDS_CAPTURE_READY               133
#define IDS_CAPTURE_NOT_READY           133
#define IDS_COMMON_FUNC_ERR             133
#define IDS_CAPTURE_START_ERR           134
#define IDS_COPY_PPT_FILE_ERR           135
#define IDS_PPT_OVER                    136
#define IDR_PREVIEW_MENU                137
#define IDB_DARK_LIGHT                  139
#define IDB_GREEN_LIGHT                 140
#define IDB_ORANGE_LIGHT                141
#define IDB_RED_LIGHT                   142
#define IDR_MAINFRM                     144
#define IDI_ICON_WARNING                146
#define IDB_ZOOM_IN                     147
#define IDS_NO_PPT_CTRL                 148
#define IDB_ZOOM_OUT                    148
#define IDD_DIALOG_PEN_PROPERTY         149
#define IDB_ARROW                       152
#define IDC_HAND                        153
#define IDB_PTR_FIRST                   162
#define IDB_PTR_P1                      162
#define IDB_PTR_P2                      163
#define IDB_PTR_P3                      164
#define IDB_PTR_P4                      165
#define IDB_PTR_P5                      166
#define IDB_PTR_P6                      167
#define IDB_PTR_P7                      168
#define IDB_PTR_P8                      169
#define IDB_PTR_C1                      170
#define IDB_PTR_C2                      171
#define IDB_PTR_C3                      172
#define IDB_PTR_C4                      173
#define IDB_PTR_C5                      174
#define IDB_PTR_D1                      175
#define IDB_PTR_D2                      176
#define IDB_PTR_D3                      177
#define IDB_PTR_D4                      178
#define IDB_PTR_E1                      179
#define IDB_PTR_E2                      180
#define IDB_PTR_E3                      181
#define IDB_PTR_E4                      182
#define IDB_PTR_E5                      183
#define IDB_PTR_E6                      184
#define IDB_PTR_F1                      185
#define IDB_PTR_F2                      186
#define IDB_PTR_F3                      187
#define IDB_PTR_F4                      188
#define IDB_PTR_F5                      189
#define IDB_PTR_F6                      190
#define IDB_PTR_F7                      191
#define IDB_PTR_F8                      192
#define IDB_PTR_G1                      193
#define IDB_PTR_G2                      194
#define IDB_PTR_G3                      195
#define IDB_PTR_G4                      196
#define IDB_PTR_G5                      197
#define IDB_PTR_G6                      198
#define IDB_PTR_H1                      199
#define IDB_PTR_H2                      200
#define IDB_PTR_H3                      201
#define IDB_PTR_H4                      202
#define IDB_PTR_I1                      203
#define IDB_PTR_I2                      204
#define IDB_PTR_I3                      205
#define IDB_PTR_LAST                    205
#define IDB_CHECK                       342
#define IDB_SPACE                       343
#define IDB_NOTE_EN                     345
#define IDB_NOTE_DIS                    346
#define IDB_UNKNOWN                     368
#define IDB_STOP                        369
#define IDB_PAUSE                       370
#define IDB_CLOSE                       374
#define IDB_PREV                        375
#define IDB_FIRST                       376
#define IDB_LAST                        377
#define IDB_REC                         378
#define IDB_VIEW                        379
#define IDB_HELP                        380
#define IDB_PREVIEW                     382
#define IDB_OPEN                        383
#define IDB_GOTO                        384
#define IDB_DEMO                        385
#define IDB_CAPTURE                     386
#define IDB_REC_DEMO                    387
#define IDB_STOP_DEMO                   388
#define IDB_RECT                        389
#define IDB_LINE                        390
#define IDB_ERASER                      391
#define IDB_PEN_SET                     392
#define IDB_POINTER                     393
#define IDB_FREE_HAND                   394
#define IDB_NG                          440
#define IDD_VOLUMEBARTESTER_DIALOG      441
#define IDD_COUNT_DOWN                  443
#define IDB_MAXTOMIN                    444
#define IDB_MINTOMAX                    445
#define IDC_BUTTON1                     1000
#define IDC_EDIT2                       1003
#define IDC_BUTTON_EXIT_GEN             1004
#define IDC_BUTTON_EXIT                 1005
#define IDC_STATIC_GRID                 1005
#define IDC_BUTTON_CANCEL               1006
#define ID_GO                           1006
#define IDC_BUTTON_OVERWRITE            1007
#define IDC_BUTTON_APPEND               1008
#define IDC_LIST_FILE                   1009
#define IDC_COMBO_WIDTH                 1010
#define IDC_COMBO_IMAGE                 1014
#define IDC_PROGRESS_Right              1016
#define IDC_PROGRESS_Left               1018
#define IDC_STATIC_CNTDWN               1019
#define IDC_SCREEN2VIDEOCTRL1           1020
#define IDC_BUTTON_COLOR                1085
#define IDC_CURSOR_DRAG_DROP            10006
#define IDC_CURSOR_DRAG_SIDE            10007
#define ID_PREVIEW_VOICE                32781
#define IDS_AUTOMATIC                   51400
#define IDS_MORE_COLOR                  51401
#define IDS_PPT_OLE_NOT_FOUND           51471
#define IDS_DISK_FREE_LOW               51495
#define IDS_ERROR_COM_WMX_UTILITY       51509
#define IDS_REGISTER_ERR                61231
#define IDS_ATTACH_WND_ERR              61232
#define IDS_COM_CAPTURE_NOT_REGISTERED  61233
#define IDS_COM_PROFILE_NOT_REGISTERED  61234
#define IDS_STOP_REC_NOW                61235
#define IDS_PPT_NOT_OPEN                61236
#define IDS_CLOSE_NOW                   61237
#define IDS_PPT_OPEN_PPT_ERROR          61238
#define IDS_CANNOT_LOAD_DLL             61239
#define IDS_STOP_REC_SCREEN_NOW         61240
#define IDS_PPT_SAVE_MEDIA_ERROR        61302
#define ID_BTN_ZOOM_IN                  61303
#define ID_BTN_ZOOM_OUT                 61304
#define ID_BTN_GOTO                     61305
#define IDS_UNDEFINED                   61306
#define IDS_END_OF_SLIDE                61307
#define IDS_STOP_REC_AND_CLOSE_PPT_NOW  61308
#define IDS_CLOSE_PPT_NOW               61309
#define ID_BTN_REC_DEMO                 61310
#define ID_BTN_STOP_DEMO                61311
#define IDS_RECAPTURE                   61312
#define IDS_STOP_TO_DEMO                61313
#define IDS_MUST_REC_FIRST              61314
#define IDS_START_RECORD                61315
#define IDS_FAIL_TO_FIND_DEVICE         61316
#define IDS_PPT_FILE_NOT_EXIST          61317
#define IDS_TIME_UP                     61319
#define ID_BTN_RECT                     61320
#define ID_BTN_LINE                     61321
#define ID_BTN_ERASER                   61322
#define ID_BTN_PENSET                   61323
#define ID_BTN_POINTER                  61325
#define ID_BTN_FREEHAND                 61326
#define IDS_STOP_AND_NG                 61327
#define IDS_NOTHING_TO_NG               61328
#define IDS_SURE_TO_NG                  61329
#define IDS_COURSE_WITHVIDEO            61329
#define ID_BTN_MAXTOMIN                 61331
#define ID_BTN_MINTOMAX                 61332
#define IDS_MIC_EMPTY                   61333
#define IDS_CAMERA_EMPTY                61334
#define IDS_CANNOT_MOVETO_SCREEN        61335
#define ID_STATIC                       65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        451
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1021
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
