#if !defined(AFX_SCREEN2VIDEO1_H__0950D631_B319_4AC8_B5D3_BFE94BC647BC__INCLUDED_)
#define AFX_SCREEN2VIDEO1_H__0950D631_B319_4AC8_B5D3_BFE94BC647BC__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVideoCompressors;
class CAudioCompressors;
class CWMVProfiles;
class CAudioInputPins;
class CAudioDevices;

/////////////////////////////////////////////////////////////////////////////
// CScreen2Video wrapper class

class CScreen2Video : public CWnd
{
protected:
	DECLARE_DYNCREATE(CScreen2Video)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xc1e943ed, 0x5a44, 0x4688, { 0x94, 0x4c, 0x9b, 0x7c, 0x3c, 0x82, 0x51, 0x3b } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	short GetVideoCompressor();
	void SetVideoCompressor(short);
	CVideoCompressors GetVideoCompressors();
	void SetVideoCompressors(LPDISPATCH);
	CString GetFileName();
	void SetFileName(LPCTSTR);
	BOOL GetUseVideoCompressor();
	void SetUseVideoCompressor(BOOL);
	BOOL GetCaptureAudio();
	void SetCaptureAudio(BOOL);
	short GetAudioCompressor();
	void SetAudioCompressor(short);
	BOOL GetUseAudioCompressor();
	void SetUseAudioCompressor(BOOL);
	CAudioCompressors GetAudioCompressors();
	void SetAudioCompressors(LPDISPATCH);
	short GetWMVProfile();
	void SetWMVProfile(short);
	CWMVProfiles GetWMVProfiles();
	void SetWMVProfiles(LPDISPATCH);
	CString GetWMVCustomProfile();
	void SetWMVCustomProfile(LPCTSTR);
	short GetCaptureLeft();
	void SetCaptureLeft(short);
	short GetCaptureTop();
	void SetCaptureTop(short);
	short GetCaptureWidth();
	void SetCaptureWidth(short);
	short GetCaptureHeight();
	void SetCaptureHeight(short);
	CString GetLicenseKey();
	void SetLicenseKey(LPCTSTR);
	BOOL GetCaptureCursor();
	void SetCaptureCursor(BOOL);
	short GetFps();
	void SetFps(short);
	CAudioInputPins GetAudioInputPins();
	void SetAudioInputPins(LPDISPATCH);
	short GetAudioInputPin();
	void SetAudioInputPin(short);
	short GetAudioDevice();
	void SetAudioDevice(short);
	CAudioDevices GetAudioDevices();
	void SetAudioDevices(LPDISPATCH);
	long GetCaptureHWND();
	void SetCaptureHWND(long);
	long GetSWFAudioBitrate();
	void SetSWFAudioBitrate(long);
	long GetSWFAudioChannels();
	void SetSWFAudioChannels(long);
	long GetSWFAudioSampleRate();
	void SetSWFAudioSampleRate(long);
	short GetSWFOutputWidth();
	void SetSWFOutputWidth(short);
	short GetSWFOutputHeight();
	void SetSWFOutputHeight(short);
	long GetSWFVideoBitrate();
	void SetSWFVideoBitrate(long);
	long GetOutputType();
	void SetOutputType(long);
	long GetFLVAudioBitrate();
	void SetFLVAudioBitrate(long);
	long GetFLVAudioChannels();
	void SetFLVAudioChannels(long);
	long GetFLVAudioSampleRate();
	void SetFLVAudioSampleRate(long);
	long GetFLVVideoBitrate();
	void SetFLVVideoBitrate(long);
	short GetFLVOutputHeight();
	void SetFLVOutputHeight(short);
	short GetFLVOutputWidth();
	void SetFLVOutputWidth(short);

// Operations
public:
	BOOL Start();
	void Stop();
	short ScreenWidth();
	short ScreenHeight();
	BOOL RefreshAudioInputPin(short iAudioDeviceIndex);
	void Pause();
	void Resume();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SCREEN2VIDEO1_H__0950D631_B319_4AC8_B5D3_BFE94BC647BC__INCLUDED_)
