#if !defined(AFX_VIDEOCOMPRESSORS1_H__6B19B610_EBC6_481C_96F1_E27C6DDEB97D__INCLUDED_)
#define AFX_VIDEOCOMPRESSORS1_H__6B19B610_EBC6_481C_96F1_E27C6DDEB97D__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVideoCompressors wrapper class

class CVideoCompressors : public COleDispatchDriver
{
public:
	CVideoCompressors() {}		// Calls COleDispatchDriver default constructor
	CVideoCompressors(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVideoCompressors(const CVideoCompressors& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetCount();
	void SetCount(short);

// Operations
public:
	short FindVideoCompressor(LPCTSTR strName);
	CString FindVideoCompressorName(short index);
	LPDISPATCH GetItem(const VARIANT& Key);
	BOOL ShowPropertyPage(short iIndex);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VIDEOCOMPRESSORS1_H__6B19B610_EBC6_481C_96F1_E27C6DDEB97D__INCLUDED_)
