#if !defined(AFX_WMVPROFILES1_H__C4AA4D56_35D2_4B02_8FAE_F36B04CD8F59__INCLUDED_)
#define AFX_WMVPROFILES1_H__C4AA4D56_35D2_4B02_8FAE_F36B04CD8F59__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CWMVProfiles wrapper class

class CWMVProfiles : public COleDispatchDriver
{
public:
	CWMVProfiles() {}		// Calls COleDispatchDriver default constructor
	CWMVProfiles(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CWMVProfiles(const CWMVProfiles& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetCount();
	void SetCount(short);

// Operations
public:
	short FindWMVProfile(LPCTSTR strProfile);
	CString FindWMVProfileDesc(short index);
	CString FindWMVProfileName(short index);
	LPDISPATCH GetItem(const VARIANT& Key);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_WMVPROFILES1_H__C4AA4D56_35D2_4B02_8FAE_F36B04CD8F59__INCLUDED_)
