//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CourseLoader.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_COURSELOADER_DIALOG         102
#define IDS_FAIL_TO_COPY                102
#define IDS_FAIL_TO_CREATE_DIR          103
#define IDS_SURE_TO_LAUNCH              104
#define IDS_SEL_COURSE_FIRST            105
#define IDS_INVALID_URL                 107
#define IDS_EXCEPTION                   108
#define IDR_MAINFRAME                   128
#define IDR_MAIN                        129
#define IDS_COURSE_DUP                  130
#define IDD_DIALOG_SQL                  130
#define IDB_TOOLBAR_HOT                 131
#define IDD_DIALOG_TYPE_SETTING         131
#define IDB_TOOLBAR_COLD                132
#define IDI_INFO                        132
#define IDD_DIALOG_REGEN_INDEX          133
#define IDD_DIALOG_INPUT_INFO           134
#define IDC_HAND                        153
#define IDD_DIALOG_MEDIA_SRV_FTP        170
#define IDD_DIALOG_PROGRESS             173
#define IDB_OPEN                        187
#define IDD_DIALOG_WEB_SRV_FTP          211
#define IDD_DIALOG_TRANS_COURSE         212
#define IDD_DIALOG_ASK_COURSE           213
#define IDD_DIALOG_OPTION               214
#define IDD_DIALOG_LAUNCH_OK            215
#define IDD_DIALOG_TYPE_SELECTING       216
#define IDD_DIALOG_COURSE_DUP           217
#define IDD_DIALOG_VIEW_SEL             218
#define IDD_DIALOG_TYPE_SET             232
#define IDD_DIALOG_ASK_TYPE             233
#define IDD_DIALOG_INPUT_PROFILE        234
#define IDB_NOTE_EN                     345
#define IDB_NOTE_DIS                    346
#define IDB_UNKNOWN                     368
#define IDB_CHECK                       369
#define IDB_UNCHECK                     370
#define IDC_LIST_MAIN                   1000
#define IDC_EDIT_COURSE                 1000
#define IDC_ANIMATE                     1000
#define IDC_COMBO_COURSE                1003
#define IDC_LOAD                        1004
#define IDC_EDIT_MSRV_ALIAS             1005
#define IDC_EDIT_MSRV_IP                1006
#define IDC_EDIT_MSRV_LOGIN_NAME        1007
#define IDC_EDIT_MSRV_PASSWORD          1008
#define IDC_EDIT_MSRV_DIRECTORY         1009
#define IDC_EDIT_MMS                    1010
#define IDC_EDIT_COURSENAME             1011
#define IDC_EDIT_MSRV_PORT              1011
#define IDC_EDIT_COURSE_URL             1012
#define IDC_EDITSQL                     1013
#define IDC_EDIT_WEBSRV_PORT            1013
#define IDC_CHECK_AUTO_TRANSFER         1014
#define IDC_CHECK_PASSIVE               1015
#define IDC_STATIC_GRID                 1016
#define IDC_BUTTON_DEL                  1017
#define IDC_BUTTON_INS                  1018
#define IDC_EDIT_LINK                   1019
#define ID_VIEW_RESULT                  1020
#define IDC_EDIT_ORG                    1020
#define IDC_BUTTON_RESERVE              1021
#define IDC_LIST_TYPE                   1021
#define IDC_EDIT_DESC                   1021
#define IDC_BUTTON_OVERWRITE            1022
#define IDC_BUTTON_SELECTALL            1022
#define IDC_PROGRESS1                   1022
#define IDC_EDIT_KEYWORD                1022
#define IDC_BUTTON_SELECT               1023
#define IDC_CHECK_CONV_DEMO             1023
#define IDC_LIST_COURSE                 1023
#define IDC_RADIO_FTP                   1024
#define IDC_CHECK_DEFAULT_SCORN         1024
#define IDC_RADIO_FTP_MANUAL            1025
#define IDC_EDIT_PATH_FTP               1026
#define IDC_RADIO_FTP_LOCAL             1027
#define IDC_EDIT_PATH_LOCAL             1028
#define IDC_EDIT_PATH_LOAD_LATER        1028
#define IDC_RADIO_SCORM                 1029
#define IDC_BUTTON_SELECT_ALL           1030
#define IDC_BUTTON_DESELECT_ALL         1031
#define IDC_BUTTON_SET_TYPE             1032
#define IDVIEW                          1033
#define IDC_BUTTON_INPUT_INFO           1033
#define IDC_TAB                         1034
#define IDC_EDIT_PATH_SCORM             1034
#define IDC_COMBO_TYPE                  1035
#define IDC_BUTTON_NEW_TYPE             1036
#define IDC_RADIO_SCORM_FTP             1036
#define IDC_BUTTON_RENAME_TYPE          1037
#define IDC_RADIO_SCORM_LOCAL           1037
#define IDC_RADIO_ORIGINAL              1038
#define IDC_RADIO_NO_SCORM              1038
#define IDC_RADIO_CONVERT               1039
#define IDC_EDIT_PATH_DIRECT            1039
#define IDC_BUTTON_DEL_TYPE             1040
#define IDC_STATIC_CODEC                1041
#define IDC_STATIC_SCREEN_TYPE          1042
#define IDC_EDIT_TYPE                   1043
#define IDC_CHECK_SCORN                 1044
#define IDC_EDIT_TITLE                  1046
#define IDC_EDIT_SUB_TITLE              1048
#define IDC_CHECK_ORACLE                1048
#define IDOnOK                          1049
#define IDC_RAD_AENRICH                 1051
#define IDC_RAD_DEFAULT                 1052
#define IDC_RAD_ORACLE                  1055
#define IDC_RAD_ORACLEOLD               1056
#define IDC_EDIT_WEBSRV_IP              1057
#define IDC_CHECK_ENHANCE               1057
#define IDC_EDIT_WEBSRV_LOGIN_NAME      1058
#define IDC_MEDIA_IN_ZIP                1058
#define IDC_EDIT_WEBSRV_PASSWORD        1059
#define IDC_EDIT_WEBSRV_DIRECTORY       1060
#define IDC_STATIC_MSG                  1063
#define IDC_RAD_ZIP1                    1076
#define IDC_RAD_ZIP6                    1077
#define IDC_RAD_ZIP9                    1078
#define IDC_RAD_MMS                     1082
#define IDC_RAD_RTSP                    1083
#define IDC_RAD_HTTP                    1084
#define IDC_RAD_HTTPNM                  1085
#define IDC_RADIO_OVERWRITE             1111
#define IDC_RADIO_NEW_NAME              1112
#define IDC_EDIT_NAME                   1113
#define IDC_STATIC_EXIST                1116
#define IDC_EDIT_DEFAULT_PROFILE        1151
#define IDC_EDIT_SCREEN_PROFILE         1152
#define IDC_BUTTON_RENAME               1158
#define IDC_EDIT_PROFILE                1159
#define IDC_COMBO_CODEC                 1160
#define IDC_BUTTON_DELETE               1161
#define IDC_CURSOR_DRAG_DROP            10006
#define IDC_CURSOR_DRAG_SIDE            10007
#define ID_EXIT                         32771
#define ID_ABOUT                        32772
#define ID_IE                           32773
#define ID_SERVER_SETTING               32774
#define ID_TYPE_SETTING                 32775
#define ID_TRANSMIT                     32776
#define ID_OPTION                       32777
#define ID_VIEW_COURSE                  32779
#define IDS_CANCEL                      51217
#define IDS_ERROR_COM_EASY_UTIL         51277
#define IDS_ERROR_COM_WMX_UTILITY       51278
#define IDS_FAIL_TO_CONVERT_ASF         51464
#define IDS_OPTION_SETTING_CAPTION      51465
#define IDS_SRV_SETTING_CAPTION         51465
#define IDS_SET_MEDIA_SRV_ALIAS         51466
#define IDS_APPNAME                     51467
#define IDS_FAIL_TO_CONNECT_INTERNET    51468
#define IDS_FAIL_TO_CHANGE_DIR          51469
#define IDS_FAIL_TO_CREATE_FTP_DIR      51471
#define IDS_GEN_MEDIA_FILE              51472
#define IDS_PROCESSING                  51473
#define IDS_COPY_FILE                   51474
#define IDS_CONVERT_FILE                51475
#define IDS_CONNECT_TO_FTP              51476
#define IDS_COPY_FILE_TO_FTP            51477
#define IDS_TRANSMIT_FILE               51478
#define IDS_FAIL_TO_FIND_FILE           51479
#define IDS_FAIL_TO_WRITE_DB            51480
#define IDS_CHECK_FREQ_FIRST            51481
#define IDS_DESCRIPTION                 51482
#define IDS_VIDEO_FREQ                  51483
#define IDS_AUDIO_FREQ                  51484
#define IDS_FRAME_RATE                  51485
#define IDS_WEB_FTP_NOT_SET             51486
#define IDS_MEDIA_FTP_NOT_SET           51487
#define IDS_FAIL_TO_PUT_FILE            51488
#define IDS_SURE_TO_EXIT                51489
#define IDS_TYPE_DESC0                  51490
#define IDS_TYPE_DESC1                  51491
#define IDS_TYPE_DESC2                  51492
#define IDS_NOT_NULL                    51493
#define IDS_COURSE_TRANSMITTED          51494
#define IDS_SELECT_ROW_FIRST            51495
#define IDS_DEFAULT_LINK                51496
#define IDS_NOT_TRANS_ANY_COURSE        51497
#define IDS_SET_COURSE_URL_FIRST        51498
#define ID_BTN_OPEN_FTP                 51499
#define ID_BTN_OPEN_FILE                51500
#define IDS_INPUT_DEST_FIRST            51501
#define IDS_DEST_NOT_EXIST              51502
#define IDS_COURSE_PUBLISHED            51503
#define IDS_NONEED                      51504
#define IDS_VIDEO_CAPTURE               57345
#define IDS_SCREEN_CAPTURE              57346
#define IDS_PROFILE_NAME                59427
#define IDS_LABEL_ATTRIB_VALUE          59429
#define IDS_MONO                        59430
#define IDS_UNTITLE                     59432
#define IDS_STEREO                      59433
#define IDS_VIDEO_BANDWIDTH             59455
#define IDS_VIDEO_FPS                   59456
#define IDS_VIDEO_KEY_PER_SEC           59457
#define IDS_VIDEO_QUALITY               59458
#define IDS_AUDIO_BANDWIDTH             59459
#define IDS_AUDIO_SAMPLE_RATE           59460
#define IDS_EMPTY_TYPE                  59461
#define IDS_DUP_TYPE                    59462
#define IDS_SURE_DEL                    59463
#define IDS_SEL_DEL_FIRST               59464
#define IDS_SYSTEM_DEFAULT_NOT_DEL      59465
#define IDS_SURE_DEL_PROFILE            59466
#define IDS_SEL_RENAME_FIRST            59467
#define IDS_SYSTEM_DEFAULT_NOT_REN      59468
#define IDS_PROFILE_NAME_NOT_NULL       59469
#define IDS_SYSTEM_DEFAULT_NOT_ALLOWED  59470
#define IDS_PROFILE_NAME_EXIST          59471
#define IDS_DEFAULT_PROFILE_NOT_FOUND   59472
#define IDS_SCREEN_PROFILE_NOT_FOUND    59473
#define IDS_PROFILE_LOW_BAND            59474
#define IDS_PROFILE_NO_SOUND            59475
#define IDS_COURSE_MODIFIED             59476
#define IDS_ERROR_CONVERT               59477
#define ID_BTN_OPEN_SCORM               59478
#define IDS_SCORM_LANGUAGE              59479
#define IDS_NOT_ALL_FILLED              59480
#define IDS_DECODE_SCORM_ERROR          59481
#define ID_STATIC                       65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
