#define MACRO_MAINFRM						((CMainFrame*)(AfxGetApp()->m_pMainWnd))
#define MACRO_VIEW							((CELearningView*)(((CMainFrame*)AfxGetApp()->m_pMainWnd)->GetActiveView()))
#define MACRO_COURSE_PATH					(::GetCoursePath(1)) 
#define MACRO_BACKUP_PATH					(::GetSysPath() + "Backup\\") 
#define MACRO_TEMPLATE_PATH					(::GetSysPath() + "Template\\") 
#define MACRO_EMPTY_HTM						(::GetSysPath() + "empty.htm")
#define MACRO_ORG_FILE(x)					(::GetCoursePath(1) + CString(x) + "\\video\\original.mp4")
#define MACRO_RECORD_VIDEO(x)				(::GetCoursePath(1) + CString(x) + "\\video\\video_edit.lrn")
#define MACRO_RECORD_TAG(x)					(::GetCoursePath(1) + CString(x) + "\\video\\video_tag.lrn")
#define MACRO_RECORD_AUDIO_MIX(x)			(::GetCoursePath(1) + CString(x) + "\\video\\audio_mix.lrn")
#define MACRO_RECORD_AUDIO_REPLACE(x)		(::GetCoursePath(1) + CString(x) + "\\video\\audio_replace.lrn")
#define MACRO_RECORD_VIDEO_TEXT(x)			(::GetCoursePath(1) + CString(x) + "\\video\\video_text.lrn")
#define MACRO_RECORD_VIDEO_EFFECT(x)		(::GetCoursePath(1) + CString(x) + "\\video\\video_effect.lrn")
#define MACRO_PRE_RECORD_VIDEO(x)			(::GetCoursePath(1) + CString(x) + "\\video\\pre_video_edit.lrn")
#define MACRO_PRE_RECORD_TAG(x)				(::GetCoursePath(1) + CString(x) + "\\video\\pre_video_tag.lrn")
#define MACRO_PRE_RECORD_AUDIO_MIX(x)		(::GetCoursePath(1) + CString(x) + "\\video\\pre_audio_mix.lrn")
#define MACRO_PRE_RECORD_AUDIO_REPLACE(x)	(::GetCoursePath(1) + CString(x) + "\\video\\pre_audio_replace.lrn")
#define MACRO_PRE_RECORD_VIDEO_TEXT(x)		(::GetCoursePath(1) + CString(x) + "\\video\\pre_video_text.lrn")
#define MACRO_PRE_RECORD_VIDEO_EFFECT(x)	(::GetCoursePath(1) + CString(x) + "\\video\\pre_video_effect.lrn")
#define MACRO_MP4_FILE(x)					(::GetVideoPath(x))//(::GetCoursePath(1) + CString(x) + "\\video\\default.mp4")
#define MACRO_VIDEO_DIR(x)					(::GetCoursePath(1) + CString(x) + "\\video\\")
#define MACRO_HTML_DIR(x)					(::GetCoursePath(1) + CString(x) + "\\html\\")

#define MACRO_CAPTION_FILE					(::GetSysPath() + "Profiles\\Caption\\caption1.vfx")
#define MACRO_CAPTION_FILE2					(::GetSysPath() + "Profiles\\Caption\\caption1.shr")
#define MACRO_MSAUDIO_FILE					(::GetSysPath() + "Profiles\\Profile\\msaudio.lrn")
#define MACRO_MSAUDIO_FILE_S				(::GetSysPath() + "Profiles\\Profile\\msaudio_s.lrn")

#define MACRO_MSAUDIO_RST_FILE				(::GetSysPath() + "Profiles\\Profile\\msaudio.rst")
#define MACRO_ACELP_FILE					(::GetSysPath() + "Profiles\\Profile\\acelp.lrn")
#define MACRO_ACELP_RST_FILE				(::GetSysPath() + "Profiles\\Profile\\acelp.rst")
#define MACRO_EFFECT_PATH					(::GetSysPath() + "Profiles\\Effect\\")
#define MACRO_FINAL_MP4_FILE(x)				(::GetCoursePath(1) + CString(x) + "\\html\\movie\\movie.mp4")
#define MACRO_SPT_FILE(x)					(::GetCoursePath(1) + CString(x) + "\\html\\movie\\default.spt")
#define MACRO_HTML_FILE(x)					(::GetCoursePath(1) + CString(x) + "\\default.htm")
#define MACRO_INI_FILE(x)					(::GetCoursePath(1) + CString(x) + "\\Course.ini")
#define MACRO_STEP_FILE(x)					(::GetCoursePath(1) + CString(x) + "\\html\\movie\\step.lrn")
#define MACRO_NG_FILE(x)					(::GetCoursePath(1) + CString(x) + "\\html\\movie\\NGstep.lrn")
#define MACRO_PRE_DEL_FILE(x)				(::GetCoursePath(1) + CString(x) + "\\html\\movie\\Predel.lrn")
#define MACRO_OUTLINE_FILE(x)				(::GetCoursePath(1) + CString(x) + "\\html\\movie\\outline.lrn")
#define MACRO_OUTLINETIME_FILE(x)			(::GetCoursePath(1) + CString(x) + "\\html\\movie\\outline_time.lrn")
#define MACRO_INI_PATH						(::GetSysPath() + "Elearning.ini") 
#define MACRO_SYS_FONT						(((CELearningApp*)AfxGetApp())->m_pSysFont) 
#define MACRO_SYS_FONT2						(((CELearningApp*)AfxGetApp())->m_pSysFont2) 
#define MACRO_SYS_FONT3						(((CELearningApp*)AfxGetApp())->m_pSysFont3) 
#define MACRO_SYS_FONT4						(((CELearningApp*)AfxGetApp())->m_pSysFont4) 
#define MACRO_BIN_PATH						(::GetSysPath() + "bin\\")
#define MACRO_LOGO_PATH						(::GetSysPath() + "Layout\\Logo\\")
#define MACRO_BG_PATH						(::GetSysPath() + "Layout\\BackGround\\")
#define MACRO_LAYOUT_PATH					(::GetSysPath() + "Layout\\Layout\\")
#define MACRO_TEMPLATE_PATH					(::GetSysPath() + "Template\\")
#define MACRO_PHOTO_PATH					(::GetSysPath() + "Layout\\Photos\\")
#define MACRO_TV_PATH						(::GetSysPath() + "Layout\\TV\\")
#define	MACRO_OUTLOOK_PATH					(::GetSysPath() + "Layout\\Outlook\\")
#define MACRO_PRESENT_PATH					(::GetSysPath() + "Presentation\\") 
#define MACRO_REGISTRY						"HKEY_LOCAL_MACHINE\\SOFTWARE\\eKDI\\MCG\\3.0"
#define MACRO_AUTOINI_FILE					(::GetSysPath() + "autoup.ini")
#define MACRO_SLIDE_PATH(x)					(::GetCoursePath(1) + CString(x) + "\\html\\THUMB1\\")
#define MACRO_PDF_PATH						(::GetSysPath() + "Help" + "\\" + "MCGPro_5.9-UsersGuide.pdf")
#define MACRO_JS_PATH(x)					(::GetCoursePath(1) + CString(x) + "\\html\\")
#define MACRO_DRAW_FILE(x)					(::GetCoursePath(1) + CString(x) + "\\html\\movie\\draw.lrn")
#define MACRO_DEVICEINFO_INI				(::GetSysPath() + "temp\\DeviceSetInfo.ini")
