//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by eLearning.rc
//
#define ID_REC                          3
#define IDDEL                           3
#define ID_GO                           3
#define ID_REMOVE                       3
#define ID_REG                          3
#define ID_SELECTALL                    3
#define ID_FAIL_TO_REGISTER             3
#define IDC_BUTTON_PREVIEW              4
#define ID_CHANGE_DEV                   5
#define ID_DEFAULT_PROFILE              5
#define ID_SCREEN_PROFILE               6
#define IDD_ABOUTBOX                    100
#define IDD_GOTO_SLIDE                  104
#define IDS_COM_INIT_ERR                115
#define ID_VIEW_ARRANGE                 127
#define IDS_PPT_OPEN_ERROR              127
#define IDR_MAINFRAME                   128
#define IDR_ELEARNTYPE                  129
#define IDS_LESSON_NAME                 129
#define IDB_SEP                         129
#define IDS_COURSE_DUP                  130
#define IDB_GLYPHS                      130
#define IDD_DIALOG_IE                   131
#define IDS_COURSE_NULL                 131
#define IDB_TOOLBAR_HOT                 131
#define IDD_DIALOG_BASIC                132
#define IDS_COPY_FILE1                  132
#define IDB_TOOLBAR_COLD                132
#define IDS_FAIL_TO_COPY                132
#define IDD_DIALOG_VIDEO_EDIT           133
#define IDS_COPY_FILE2                  133
#define IDB_PLAY                        133
#define IDR_MAINFRAME_KDI               133
#define IDD_DIALOG_NEW_COURSE           134
#define IDS_RENDER_SUCCESS              134
#define IDD_DIALOG_EDIT_MARK            135
#define IDS_RENDER_BEFORE               135
#define IDS_NO_PPT_FILE                 136
#define IDD_DIALOG_EDIT_DEL             136
#define IDS_PPT_ERR                     137
#define IDD_DIALOG_DEVICE               137
#define IDS_RENAME_FILE1                138
#define IDB_TV                          138
#define IDS_RENAME_FILE                 138
#define IDS_RENAME_DIR1                 139
#define IDB_PAGE                        139
#define IDS_RENAME_DIR                  139
#define IDS_UPDATE_FILE1                140
#define IDB_RED_KEY                     140
#define IDS_UPDATE_FILE                 140
#define IDB_BLUE_KEY                    141
#define IDS_COMMON_ERR                  141
#define IDS_ERR_META_DATA               142
#define IDB_GREEN_KEY                   142
#define IDS_ERR_HEAD_INFO               143
#define IDB_POINTER                     143
#define IDS_ERR_EDITOR_OPEN             144
#define IDB_PREV                        144
#define IDS_ADD_SCRIPT_ERROR            145
#define IDB_NEXT                        145
#define IDS_GRID_TITLE                  146
#define IDS_GRID_SLIDER_TITLE           146
#define IDS_NO_JPEG_FILE                147
#define IDB_MARK                        147
#define IDS_NO_PPT_CTRL                 148
#define IDB_UNMARK                      148
#define IDS_PPT_FILE                    149
#define IDB_EDIT                        149
#define IDB_CUT                         150
#define IDS_COMMON_FUNC_ERR             150
#define IDB_GO                          151
#define IDS_ASF_FILE                    151
#define IDS_GRID_ZOOM_TITLE             152
#define IDC_HAND                        153
#define IDS_MEDIA_FILE                  153
#define IDB_CUT_STATUS                  154
#define IDS_GRID_DEMO_TITLE             154
#define IDB_THUMB                       155
#define IDS_COPY_PPT_FILE_ERR           155
#define IDS_IMAGE_FILE                  156
#define IDS_HTM_FILE                    157
#define IDD_BROWSE                      158
#define IDS_WAV_FILE                    158
#define IDD_DIALOG_LAYOUT_SET           161
#define IDD_DIALOG_SETFONT              162
#define IDB_SQ_IN                       167
#define IDB_SQ_OUT                      168
#define IDD_DIALOG_OPTION_SETTING       169
#define IDD_DIALOG_MEDIA_SERVER         170
#define IDD_DIALOG_PROFILE_SETTING      171
#define IDD_DIALOG_PAGE_RECORD_OPTION   171
#define IDD_DIALOG_SET_BANDWIDTH        172
#define IDD_DIALOG_PROGRESS             173
#define IDD_DIALOG_PPT_SYNC             178
#define IDB_LOCATE                      179
#define IDD_DIALOG_NEW_COURSE_FROM_MEDIA 179
#define IDB_LOCATE_PREV                 180
#define IDD_DIALOG_ASK_DEV              180
#define IDB_LOCATE_NEXT                 181
#define IDB_CHECK                       182
#define IDB_SPACE                       183
#define IDB_PLAY_VIDEO                  184
#define IDB_PAUSE_VIDEO                 185
#define IDB_STOP_VIDEO                  186
#define IDB_OPEN                        187
#define IDB_GOTO                        188
#define IDR_MENU_CP                     189
#define IDR_MENU_DP                     190
#define IDB_MCG                         191
#define IDR_MENU_CHANGE_BMP             191
#define IDB_DEMO                        192
#define IDR_MENU_ADD_EVENT              192
#define IDR_MENU_ADD_WAVE               193
#define IDR_MENU_VIDEO_EFFECT           194
#define IDR_MENU_VIDEO_EDIT             195
#define IDD_DIALOG_SEL_COURSE           196
#define IDD_DIALOG_PROFILE_SETTING_S    197
#define IDD_DIALOG_INPUT_COURSE         198
#define IDD_DIALOG_DEFAULT_OPTION       199
#define IDB_VIDEO_PROFILE               199
#define IDD_DIALOG_DEFAULT_LAYOUT       200
#define IDB_CAPTURE_VIDEO               200
#define IDD_DIALOG_DEFAULT_IMAGE        201
#define IDB_THUMB_HEAD                  201
#define IDD_DIALOG_DEFAULT_OUTLOOK      202
#define IDB_THUMB_BODY                  202
#define IDD_DIALOG_INPUT_OUTLOOK        203
#define IDB_THUMB_TAIL                  203
#define IDD_DIALOG_MISC                 204
#define IDB_CHANGE_PPT                  204
#define IDD_DIALOG_WMV_INFO             205
#define IDB_EDIT_PPT                    205
#define IDB_REGEN_PPT                   206
#define IDD_DIALOG_SEL_BKUP             206
#define IDB_LEFT                        207
#define IDD_DIALOG_SEL_RESTORE          207
#define IDD_DIALOG_BACKUP_MAINTAIN      208
#define IDB_RIGHT_UP                    208
#define IDB_RIGHT                       209
#define IDB_LEFT_UP                     210
#define IDD_DIALOG_COURSE_DUP           210
#define IDB_RIGHT_BOTTOM                211
#define IDD_DIALOG_SEL_RESTORE1         211
#define IDD_REG_KEY                     211
#define IDB_BOTTOM                      212
#define IDD_DATE_OUT                    212
#define IDB_LEFT_BOTTOM                 213
#define IDD_DIALOG_INS_VIDEO_SRC        213
#define IDB_UP                          214
#define IDD_DIALOG_NOTE                 217
#define IDD_CHCEK_OUT                   218
#define IDD_REGISTER                    219
#define IDD_USE_QUOTA                   220
#define IDB_PPT                         220
#define IDD_DIALOG_IMPORT_COURSE        221
#define IDB_ZOOM_IN_SCALE               221
#define IDD_DIALOG_BACKUP_SETTING       222
#define IDB_ZOOM_OUT_SCALE              222
#define IDD_DIALOG_SEL_BKUP_DIR         223
#define IDB_PREV_PAGE                   223
#define IDB_NEXT_PAGE                   224
#define IDD_SEL_HTM_COURSE              225
#define IDD_DIALOG_INPUT_CAPTION        230
#define IDD_DIALOG_EXPORT               231
#define IDD_DIALOG_PROFILE_SET          232
#define IDD_DIALOG_INPUT_PROFILE        233
#define IDD_DIALOG_PROFILE_SET_S        234
#define IDD_DIALOG_CAPTION_DEFAULT      235
#define IDR_MENU_EFFECT                 237
#define IDD_DIALOG_SELECT_EFFECT        237
#define IDD_DIALOG_REC_WMV              238
#define IDD_DIALOG_CAPTURE_SCREEN       239
#define IDD_DIALOG_ADJUST               240
#define IDD_DIALOG_SEL_COURSE_VOLUME    241
#define IDD_WIZARD                      244
#define IDB_WIZARD                      246
#define IDW_SELECT_HTML                 249
#define IDW_SETUP                       250
#define IDB_OPEN2                       250
#define IDW_SELECT_PPT                  251
#define IDW_INPUT_NAME                  252
#define IDW_SELECT_DEVICE               253
#define IDW_SELECT_FREQ                 254
#define IDW_SELECT_LAYOUT               255
#define IDW_SELECT_TV                   256
#define IDD_OPEN_COURSE                 257
#define IDB_NOTE_EN                     345
#define IDB_NOTE_DIS                    346
#define IDB_UNKNOWN                     368
#define IDB_STOP                        369
#define IDB_PAUSE                       370
#define IDB_STEP_F                      371
#define IDB_STEP_B                      373
#define IDB_INSERT                      374
#define IDB_ZOOM_IN                     375
#define IDB_ZOOM_OUT                    376
#define IDB_REP_STATUS                  377
#define IDB_FIRST_SLIDE                 378
#define IDB_LAST_SLIDE                  379
#define IDB_NEXT_SLIDE                  380
#define IDB_PREV_SLIDE                  381
#define IDB_DEL_MARK                    382
#define IDB_ADD_DEMO                    383
#define IDB_REFINE                      384
#define IDB_PRACTICE                    385
#define IDB_ADD_PRACTICE                386
#define IDB_LAST                        387
#define IDB_FIRST                       388
#define IDB_DRAWMARK                    389
#define IDB_BOLD                        390
#define IDB_ITALIC                      391
#define IDB_HTM                         392
#define IDB_BOUNDARY                    393
#define IDB_HTML_KEY                    394
#define IDB_WEB                         395
#define IDB_PEN                         396
#define IDB_PEN_HOT                     397
#define IDB_ADD_EVENT                   398
#define IDB_ADD_WAVE                    399
#define IDB_MIX_WAVE                    400
#define IDB_REPLACE_WAVE                401
#define IDB_ADD_TEXT                    402
#define IDB_ADD_EFFECT                  403
#define IDB_MUTE                        405
#define IDB_SET_POINTS                  406
#define IDB_ADJUST                      408
#define IDC_EDIT_COURSE                 1000
#define IDC_COMBO_FONT                  1000
#define IDC_ANIMATE                     1000
#define IDC_COMBO_SIZE                  1001
#define IDC_EDIT_MEDIA                  1001
#define IDC_EDIT_PPT                    1002
#define IDC_STATIC_GRID                 1003
#define IDC_STATIC_SLIDE                1003
#define IDC_MOVIE_SCREEN                1005
#define IDC_STATIC_OUTLIINE             1006
#define IDC_LIST_LINK                   1007
#define IDC_COMBO_DV                    1010
#define IDC_COMBO_DV_VIDEO              1010
#define IDC_SHEETRECT                   1010
#define IDC_RADIO_DV                    1011
#define IDC_RADIO_CAM                   1012
#define IDC_COMBO_CAM_VIDEO             1013
#define IDC_COMBO_CAM_AUDIO             1014
#define IDC_EDIT_FOLDER                 1014
#define IDC_COMBO_AUDIO                 1014
#define IDC_RADIO_NO_VIDEO              1015
#define IDC_STATIC_IMAGE                1016
#define IDC_COMBO_DV_AUDIO              1016
#define IDC_COMBO_SCREEN_AUDIO          1016
#define IDC_BUTTON_DEFAULT              1017
#define IDC_STATIC_FOLDER               1018
#define IDC_CHECK_ITALIC                1018
#define ST_CAPTION                      1018
#define IDC_CHECK_BOLD                  1019
#define IDC_CHECK_UNDERLINE             1020
#define IDC_BUTTON_CHANGE_BG            1021
#define IDC_BUTTON_CHANGE_LAYOUT        1023
#define IDC_BUTTON_CHANGE_LOGO          1024
#define IDC_STATIC_LAYOUT               1026
#define IDC_STATIC_BG_LAYOUT            1027
#define IDC_STATIC_OPTION               1027
#define IDC_BUTTON_SET_BG_EMPTY         1028
#define IDC_STATIC_LOGO                 1029
#define IDC_EDIT_ADVISOR                1030
#define IDC_EDIT_COURSE_NAME            1031
#define IDC_EDIT_COOP                   1032
#define IDC_STATIC_INFO                 1033
#define IDC_STATIC_LO                   1034
#define IDC_STATIC_HTML_LO              1035
#define IDC_STATIC_BG                   1036
#define IDC_STATIC_COURSE_NAME          1037
#define IDC_STATIC_ADVISOR              1038
#define IDC_STATIC_COOP                 1039
#define IDC_TAB                         1041
#define IDC_BUTTON_DELETE               1043
#define IDC_BUTTON_ADJUST               1044
#define IDC_BUTTON_SET_FONT             1045
#define IDC_COMBO_DIM                   1046
#define IDC_COMBO_FPS                   1047
#define IDC_COMBO_VIDEO_QUALITY         1048
#define IDC_EDIT_DELAY                  1048
#define IDC_COMBO_AUDIO_QUALITY         1049
#define IDC_EDIT_A_DELAY                1049
#define IDC_COMBO_FPS_S                 1050
#define IDC_COMBO_VIDEO_QUALITY_S       1051
#define IDC_STATIC_S_DELAY              1052
#define IDC_COMBO_AUDIO_QUALITY_S       1052
#define IDC_STATIC_A_DELAY              1053
#define IDC_STATIC_SEC1                 1054
#define IDC_STATIC_SEC2                 1055
#define IDC_EDIT_IP                     1057
#define IDC_EDIT_LOGIN_NAME             1058
#define IDC_EDIT_PASSWORD               1059
#define IDC_COMBO_AF                    1061
#define IDC_STATIC_MSG                  1063
#define IDC_COMBO_VF                    1064
#define IDC_STATIC_PPT                  1065
#define IDC_EDIT_VIDEO_DEVICE           1072
#define IDC_EDIT_AUDIO_DEVICE           1073
#define ID_RETRY                        1074
#define IDC_STATIC_DEVICE               1075
#define IDC_LIST_COURSE                 1079
#define IDC_STATIC_TITLE                1080
#define IDC_LIST_OPTION                 1081
#define IDC_STATIC_TITLE2               1081
#define IDC_STATIC_COLOR_SET            1082
#define IDC_LIST_IMAGE_ITEM             1083
#define IDC_BUTTON_SAVE_AS              1084
#define IDC_BUTTON_COLOR1               1085
#define IDC_DIRTREE                     1086
#define IDC_COMBO_OUTLOOK               1086
#define IDC_STATIC_OUTLOOK_NAME         1087
#define IDC_STATIC_ITEM                 1088
#define IDC_STATIC_SIZE1                1089
#define IDC_STATIC_COLOR1               1090
#define IDC_EDIT_SIZE                   1091
#define IDC_STATIC_TV_SIZE              1092
#define IDC_COMBO_ITEM                  1093
#define IDC_STATIC_FONT                 1094
#define IDC_STATIC_SIZE2                1095
#define IDC_STATIC_COLOR2               1096
#define IDC_COMBO_FONT_SIZE             1097
#define IDC_BUTTON_COLOR2               1099
#define IDC_LIST_OUTLOOK                1101
#define IDC_STATIC_VIDEO                1104
#define IDC_STATIC_AUDIO                1105
#define IDC_STATIC_SCREEN_AUDIO         1106
#define IDC_RADIO_HIGH                  1107
#define IDC_RADIO_LOW                   1108
#define IDC_LIST_AUDIO                  1108
#define IDC_LIST_VIDEO                  1109
#define IDC_RADIO_SHIGH                 1109
#define IDC_CHECK_DEL                   1110
#define IDC_RADIO_SLOW                  1110
#define IDC_RADIO_OVERWRITE             1111
#define IDC_RADIO_NEW_NAME              1112
#define IDC_EDIT_NAME                   1113
#define IDC_STATIC_EXIST                1116
#define IDC_EDIT_CODE                   1118
#define IDC_BUTTON_RELOAD               1120
#define IDC_RADIO_RECORD                1121
#define IDC_RADIO_EXISTING_FILE         1122
#define ID_OK                           1123
#define IDC_EDIT_FILE                   1124
#define IDC_EDIT_NOTE                   1126
#define IDC_CHECK_AUDIOONLY             1128
#define IDC_STATIC_STATUS               1128
#define IDC_RADIO_LARGE                 1129
#define IDC_COMBO_VERSION               1129
#define IDC_RADIO_MEDIUM                1130
#define IDC_RADIO_SMALL                 1131
#define IDC_COMBO_DIR                   1131
#define IDC_CHECK_PNG                   1132
#define IDC_RADIO_EXLARGE               1132
#define IDC_RADIO_VOICE                 1133
#define IDC_COMBO_PRESENT               1133
#define IDC_RADIO_HUGE                  1133
#define IDC_RADIO_SCREEN                1134
#define IDC_RADIO_PPT                   1134
#define IDC_COMBO_HOT                   1135
#define IDC_RADIO_HTML                  1135
#define IDC_EDIT_LAST_NAME              1136
#define IDC_EDIT_FIRST_NAME             1137
#define IDC_EDIT_SERIAL1                1138
#define IDC_EDIT_SERIAL2                1139
#define IDC_EDIT_CAPTION_LENGTH         1139
#define IDC_EDIT_SERIAL3                1140
#define IDC_RADIO_BEST                  1140
#define IDC_EDIT_SERIAL4                1141
#define IDC_RADIO_GENERAL               1141
#define IDC_EDIT_EMAIL                  1142
#define IDC_EDIT_CAPTION                1142
#define IDC_EDIT_EFFECT_LENGTH          1142
#define IDC_EDIT_SERIAL5                1143
#define IDC_EDIT_COMPANY                1144
#define IDC_RADIO_ORIGINAL              1144
#define IDC_RADIO_AUDIO_ONLY            1145
#define IDC_RADIO_FREQ                  1146
#define IDC_EDIT_DIR                    1147
#define IDC_STATIC_EXPORT               1148
#define IDC_RADIO_DEFAULT               1149
#define IDC_EDIT_DEFAULT_PROFILE        1151
#define IDC_EDIT_SCREEN_PROFILE         1152
#define IDC_EDIT_VIDEO_CODEC            1152
#define IDC_RADIO_SIZE3                 1157
#define IDC_BUTTON_RENAME               1158
#define IDC_RADIO_SIZE2                 1159
#define IDC_EDIT_PROFILE                1159
#define IDC_RADIO_SIZE1                 1160
#define IDC_COMBO_CODEC                 1160
#define IDC_BUTTON_DEL                  1161
#define IDC_RADIO_SIZE4                 1162
#define IDC_RADIO_SIZE5                 1163
#define IDC_RADIO_SIZE6                 1164
#define IDC_RADIO_UP                    1165
#define IDC_RADIO_DOWN                  1166
#define IDC_EDIT_H_INDENT               1167
#define IDC_RADIO_TRANSPARENT           1168
#define IDC_RADIO_LEFT                  1169
#define IDC_RADIO_CENTER                1170
#define IDC_RADIO_RIGHT                 1171
#define IDC_EDIT_V_INDENT               1172
#define IDC_RADIO_OPAQUE                1173
#define IDC_BUTTON_COLOR_FG             1174
#define IDC_BUTTON_COLOR_BG             1175
#define IDC_RADIO_MIDDLE                1176
#define ID_APPLY                        1177
#define IDC_STATIC1                     1179
#define IDC_EDIT_FILE_NAME              1180
#define IDC_STATIC_ATTRIB               1181
#define IDC_SLIDER_VOLUME               1182
#define IDC_SLIDER_LIGHT                1183
#define IDC_SLIDER_CONTRAST             1184
#define IDC_EDIT_PERCENT                1184
#define IDC_COMBO_FREEHAND_UNIT         1185
#define IDC_STATIC_STEP                 1188
#define IDC_RADIO_FREQ1                 1192
#define IDC_STATIC_PICTURE              1194
#define IDC_STATIC_DC                   1197
#define IDC_RADIO_FREQ2                 1199
#define IDC_RADIO_FREQ3                 1200
#define IDC_RADIO_FREQ4                 1201
#define IDC_RADIO_FREQ5                 1202
#define IDC_RADIO_FREQ6                 1203
#define IDC_RADIO_OTHER                 1204
#define IDC_EDIT_OTHER                  1205
#define IDC_CURSOR_DRAG_DROP            10006
#define IDC_CURSOR_DRAG_SIDE            10007
#define ID_PAGE_NO_EDIT                 31775
#define ID_SLIDER                       31776
#define ID_KEY_FRAME                    31777
#define ID_DELPERIOD                    31778
#define ID_POINTER_START                31779
#define ID_POINTER_END                  31780
#define ID_LAYOUT_CELL                  31781
#define ID_LOGO_CELL                    31782
#define ID_BG_CELL                      31783
#define ID_SETTING                      32771
#define ID_REFRESH                      32772
#define ID_STOP                         32773
#define ID_NEW_LESSON                   32774
#define ID_DEL_LESSON                   32775
#define ID_UPDATE_PPT                   32776
#define ID_SUBMIT_LESSON                32777
#define ID_RECORD                       32778
#define ID_IE                           32779
#define ID_REPLACE_LOGO                 32780
#define ID_DEV_SETTING                  32781
#define ID_DEFAULT_LAYOUT               32782
#define ID_RECORD_ASF_FILE              32783
#define ID_EXPORT_AUDIO_ONLY            32784
#define ID_RENAME_COURSE                32785
#define ID_SAVE_AS                      32786
#define ID_EXPORT_COURSE                32787
#define ID_UPLOAD_COURSE                32788
#define ID_SAVE_AS_BANDWIDTH            32789
#define ID_SET_CONTROL_POINT            32790
#define ID_NEW_FROM_MEDIA               32791
#define ID_DELETE_CP                    32793
#define ID_EDIT_CP                      32794
#define ID_UNDELETE_DP                  32795
#define ID_DEMO_CAPTURE                 32796
#define ID_SET_PHOTO                    32797
#define ID_DESIGN                       32798
#define ID_VIEW_OBJ                     32799
#define ID_REPLACE_PPT_FILE             32800
#define ID_CHANGE_BMP                   32800
#define ID_OPEN_PPT_FILE                32801
#define ID_SCREEN_CAPTURE               32802
#define ID_BKUP_COURSE                  32803
#define ID_RESTORE_COURSE               32804
#define ID_BACKUP_COURSE                32805
#define ID_DEL_COURSE                   32807
#define ID_UNDELETE_ALL_DP              32808
#define ID_REMOVE_BOUND_POINTER         32810
#define ID_BACKUP_MAINTAIN              32811
#define ID_REG_CODE                     32812
#define ID_REGISTER                     32813
#define ID_ONLINE_HELP                  32814
#define ID_START_TRACE                  32816
#define ID_END_TRACE                    32817
#define ID_COURSE_UPLOADER              32820
#define ID_COURSE_LOADER                32821
#define ID_VIEW_VIDEO                   32822
#define ID_IMPORT_COURSE                32822
#define ID_CHECK_OUT                    32823
#define ID_CONTACT_US                   32824
#define ID_SERIAL_REUSE                 32825
#define ID_BUY_QUOTA                    32826
#define ID_USE_QUOTA                    32827
#define ID_HTML_PRESENT                 32829
#define ID_ADD_ZOOM_IN                  32834
#define ID_ADD_ZOOM_OUT                 32835
#define ID_ADD_HTML                     32836
#define ID_ADD_SCREEN_CAPTURE           32837
#define ID_ADD_AUDIO_REPLACE            32839
#define ID_ADD_AUDIO_MIX                32840
#define ID_DEL_OBJ                      32841
#define ID_EDIT_CONTENT                 32842
#define ID_VIDEO_UNINSERT               32846
#define ID_VIDEO_UNDELETE               32847
#define ID_EXPORT                       32848
#define ID_PROFILE_SETTING              32849
#define ID_SCREEN_PROFILE_SETTING       32850
#define ID_UNDO                         32851
#define ID_REDO                         32852
#define ID_FADE_IN                      32853
#define ID_FADE_OUT                     32854
#define ID_TRANSIT_EFFECT               32856
#define ID_DELETE_ALL_CP                32857
#define ID_IMPORT_DEMO_FILE             32858
#define ID_SAVE_VIDEO                   32859
#define ID_BATCH_VOLUME                 32860
#define ID_NEW_WIZARD                   32861
#define ID_OPEN                         32862
#define IDS_STOP                        51204
#define IDS_PLAY                        51205
#define IDS_PAUSE                       51206
#define IDS_STEP_FORWARD                51207
#define IDS_STEP_BACKWARD               51208
#define IDS_S_STOP                      51209
#define IDS_RUNNING                     51210
#define IDS_LOADING                     51211
#define IDS_READY                       51212
#define IDS_FAIL_TO_RENDER              51213
#define IDS_NO_FILE                     51214
#define IDS_NO_COURSE                   51215
#define IDS_CANNOT_EXEC_EXE             51216
#define IDS_CANCEL                      51217
#define IDS_FIRST_LOAD                  51218
#define IDS_LOAD_PPT                    51219
#define IDS_SAVE_JPG                    51220
#define IDS_SAVE_HTM                    51221
#define IDS_SAVE_OUTLINE                51222
#define IDS_CLOSE_PPT                   51223
#define IDS_NO_SEL_COURSE               51224
#define IDS_DEL_CONFIRM                 51225
#define IDS_COURSE_DELETED              51226
#define IDS_COURSE_CANNOT_DELETED       51227
#define IDS_UPDATE_PPT_CONFIRM          51228
#define IDS_DEL_BEFORE_REC              51229
#define IDS_REGISTER_ERR                51231
#define IDS_S_PLAY                      51232
#define IDS_S_PAUSE                     51233
#define IDS_LABEL_SLIDER                51234
#define IDS_LABEL_KEY_FRAME             51235
#define IDS_LABEL_DELETE                51236
#define IDS_INVALID_COURSE              51237
#define IDS_CONVERT_AVI                 51238
#define IDS_CONVERTING_FILE             51239
#define IDS_CONVERTFILES                51240
#define ID_BTN_PREV                     51242
#define ID_BTN_NEXT                     51243
#define ID_BTN_MARK                     51244
#define ID_BTN_UNMARK                   51245
#define ID_BTN_PREV_PAGE                51245
#define ID_BTN_DELETEGO                 51246
#define ID_BTN_EDITDEL                  51247
#define ID_BTN_EDITMARK                 51248
#define ID_BTN_DELETE                   51249
#define IDS_RECOVER_DELETED             51250
#define IDS_GRID_TITLE_DELP             51251
#define IDS_TIME_ERROR_LINE_I           51252
#define IDS_TIME_ERROR_LINE_SEQ         51253
#define IDS_SELECT_FIRST                51254
#define IDS_TIME_ERROR_OVER             51255
#define IDS_CHANGE_TAGGING              51256
#define IDS_TAG_ASF                     51257
#define IDS_REMOVING_MARKER             51258
#define ID_BTN_DEMO                     51258
#define IDS_REMOVING_SCRIPT             51259
#define IDS_RECOVER_ALL_DELETED         51259
#define IDS_ADDING_MARKER               51260
#define ID_BTN_LAST                     51260
#define IDS_ADDING_SCRIPTS              51261
#define ID_BTN_NEXT_PAGE                51261
#define IDS_FLUSHING                    51262
#define IDS_NO_DV                       51263
#define IDS_DV_SELECTED                 51264
#define IDS_CAM_SELECTED                51265
#define IDS_NO_SEL_BEFORE               51266
#define IDS_NO_KEY                      51267
#define IDS_BOTH_MARKED                 51268
#define IDS_NOT_MARK_COMPLETE           51269
#define IDS_NOT_MARK_COMPLETE_FOR_CUT   51269
#define IDS_NO_IMAGE_SELECTED           51270
#define IDS_SEL_IMAGE                   51271
#define IDS_LOADING_IMAGE               51272
#define IDS_LAYOUT_SELECT               51273
#define IDS_BG_SELECT                   51274
#define IDS_LOGO_SELECT                 51275
#define IDS_NO_DEFAULT_LOGO             51276
#define IDS_ERROR_COM_EASY_UTIL         51277
#define IDS_ERROR_COM_EASY_EDIT         51278
#define IDS_SURE_GO_DEL                 51279
#define IDS_NOTHING_TO_CUT              51280
#define ID_BTN_REPLACE                  51281
#define IDS_DELETED_PERIOD              51282
#define IDS_REPLACED_PERIOD             51283
#define IDS_GRID_TITLE_UPD              51284
#define IDS_OVERLAPPED_ERROR            51285
#define IDS_FILE_NOT_EXIST_ERROR        51286
#define IDS_OVERLAP_PERIOD              51287
#define IDS_SLIDER_DELETED              51288
#define ID_BTN_ZOOMIN                   51289
#define ID_BTN_ZOOMOUT                  51290
#define IDS_ZOOM_IN                     51291
#define IDS_ZOOM_OUT                    51292
#define IDS_MARK_ZOOMIN_ERROR           51293
#define IDS_MARK_ZOOMOUT_ERROR          51294
#define IDS_SURE_TO_ZOOM_IN             51295
#define IDS_ERROR_COM_EASY_PLAY         51295
#define IDS_SURE_TO_ZOOM_OUT            51296
#define IDS_NOT_MARK_COMPLETE_FOR_MUTE  51296
#define IDS_INVALID_FOR_ZOOM_IN         51297
#define IDS_SURE_TO_ADD_CP              51297
#define IDS_INVALID_FOR_ZOOM_OUT        51298
#define IDS_PHOTO_SELECT                51298
#define IDS_SLIDER_POINT                51299
#define IDS_ZOOM_POINT                  51300
#define IDS_ZOOM_TYPE_ERROR             51301
#define IDS_TYPE_ERROR                  51301
#define IDS_DEMO                        51302
#define IDS_EXPORT_AUDIO_ERROR          51303
#define IDS_EXPORT_BANDWIDTH_ERROR      51303
#define IDS_DUMP_KEY_ERROR              51304
#define IDS_COURSE_EXPORT_OK            51305
#define IDS_AUDIO_ONLY                  51306
#define IDS_RENAME_COURSE_ERROR         51307
#define IDS_RENAME_COURSE_OK            51308
#define IDS_COURSE_SAVE_AS_OK           51309
#define IDS_SELECT_FOLDER               51310
#define IDS_SURE_TO_EXPORT              51311
#define IDS_OPTION_CAPTION              51312
#define IDS_PROFILE_UNMATCH             51313
#define IDS_LOADING_IMAGE_SET           51313
#define IDS_FILE_PROFILE_NOT_MATCH_ERROR 51314
#define IDS_CONTROL_POINT_EXISTS        51315
#define IDS_TIME_ERROR_DUP              51316
#define IDS_TIME_ERROR_DUP_P            51317
#define IDS_CONNECT_FTP_ERROR           51318
#define IDS_SET_SRV_BEFORE_UPLOAD       51319
#define IDS_UPLOAD_SUCCEED              51320
#define IDS_UPLOAD_FAIL                 51321
#define IDS_FAIL_TO_CREATE_REMOTE_DIR   51322
#define IDS_VIDEO_FREQ_MUST_INPUT       51323
#define IDS_AUDIO_FREQ_MUST_INPUT       51324
#define IDS_FPS_MUST_INPUT              51325
#define IDS_LOW_BAND                    51326
#define IDS_DELAY_ERROR                 51327
#define IDS_ADJUST_OUT_OF_RANGE         51328
#define IDS_FAIL_TO_REMOVE_HTML_DIR     51329
#define IDS_PATH_LOCKED                 51330
#define IDS_PROCESSING                  51331
#define IDS_MODIFY_CONTROL_POINT        51332
#define IDS_CUTTING_VIDEO               51333
#define IDS_EXPORT_TO_VAR_BANDWIDTH     51334
#define IDS_EXPORT_TO_AUDIO_ONLY        51335
#define IDS_SAVING_AS                   51336
#define IDS_EXPORTING_COURSE            51337
#define IDS_FAIL_TO_CREATE_DIR          51338
#define IDS_KEY_FILE_NOT_EXIST          51339
#define IDS_DUMPING_KEY                 51340
#define IDS_PPT_IS_RUNNING              51341
#define ID_BTN_FIRST_SLIDE              51342
#define ID_BTN_LAST_SLIDE               51343
#define ID_BTN_NEXT_SLIDE               51344
#define ID_BTN_PREV_SLIDE               51345
#define IDS_OLE_INIT_FAILED             51346
#define IDS_SLIDE_OUT_OF_RANGE          51347
#define IDS_CONVERT_ERROR               51348
#define IDS_LAST_SLIDE                  51349
#define IDS_CANNOT_LOAD_DLL             51350
#define ID_BTN_LOCATE                   51351
#define ID_BTN_LOCATE_PREV              51352
#define ID_BTN_LOCATE_NEXT              51353
#define IDS_STOP_RUNNING_FIRST          51354
#define ID_BTN_OPEN_MEDIA               51355
#define ID_BTN_OPEN_PPT                 51356
#define IDS_PPT_FILE_NULL               51357
#define IDS_MEDIA_FILE_NULL             51358
#define IDS_FILE_NOT_FOUND              51359
#define IDS_COPY_FILES                  51360
#define IDS_TIME_MARKED_BEFORE          51361
#define IDS_NO_CONTROL_POINT            51362
#define ID_BTN_GOTO                     51363
#define IDS_UNDEFINED                   51364
#define IDS_NOT_CHANGE_SLIDE            51365
#define IDS_FILE_IS_MARKED              51366
#define ID_BTN_DEL_MARK                 51367
#define IDS_DEL_CONTROL_POINT           51368
#define IDS_SURE_TO_REMOVE_ALL_CP       51369
#define IDS_DEL_SAME_SLIDE              51370
#define IDS_ASSOCIATED_WITH             51371
#define IDS_UPLOADING_COURSE            51372
#define IDS_HTML_FILE_NULL              51372
#define IDS_FAIL_TO_LOAD_FILE           51373
#define IDS_CONVERT_WMV_TO_ASF          51374
#define IDS_CREATE_INDEX                51375
#define IDS_FAIL_TO_GET_SCRIPT          51376
#define IDS_GEN_COURSE                  51377
#define IDS_SLIDE_NO                    51378
#define IDS_DEMO_POINT                  51379
#define IDS_DEFAULT_COURSE              51380
#define IDS_DEFAULT_ADVISOR             51381
#define ID_BTN_OPEN_DIR                 51381
#define IDS_COURSE_RELOAD               51382
#define IDS_ERROR_COM_EASY_CONVERT      51383
#define IDS_SELECT_TO_EXPORT            51384
#define IDS_EXPORT_COMPLETE             51385
#define IDS_PRACTICE_POINT              51386
#define IDS_DEMO_PT                     51387
#define IDS_TV_SELECT                   51387
#define IDS_DEMO_EXIST                  51388
#define IDS_FAIL_TO_OPEN_DEVICE         51389
#define IDS_SET_PHOTO                   51390
#define IDS_SURE_TO_DELETE              51390
#define IDS_FAIL_TO_FIND_DEVICE         51391
#define IDS_ERROR_COM_MEDIA_CONVERT     51391
#define ID_BTN_STEP                     51392
#define ID_BTN_ADD_PRACTICE             51393
#define IDS_PRACTICE                    51394
#define IDS_PRACTICE_EXIST              51395
#define IDS_FILE_NOT_EXIST              51396
#define IDS_PPT_NOT_EXIST_AND_SEL       51397
#define IDS_NO_PPT_SET                  51398
#define ID_IMAGE_CELL                   51399
#define IDS_AUTOMATIC                   51400
#define IDS_MORE_COLOR                  51401
#define IDS_OPTION_FRAME_BORDER         51402
#define IDS_LOGO_PICTURE                51403
#define IDS_BG_IMAGE                    51404
#define IDS_TV_IMAGE                    51405
#define IDS_ADVISOR_PHOTO               51406
#define IDS_OPTION_STATUS_BAR           51407
#define IDS_OPTION_SHOW_TIME            51408
#define IDS_OPTION_SHOW_HEADNO          51409
#define IDS_OPTION_HYPER_UNDERLINE      51410
#define IDS_DEFAULT_SETTING_CAPTION     51411
#define IDS_VIDEO_REGION                51412
#define IDS_HYPER_LINK                  51413
#define IDS_LOGO                        51414
#define IDS_SLIDE                       51415
#define IDS_ADVISOR_MESSAGE             51416
#define IDS_HIGH_LIGHT                  51417
#define IDS_COURSE_NAME                 51418
#define IDS_OPTION_BG_IMAGE             51419
#define IDS_HOT_LINK                    51420
#define IDS_SEP                         51421
#define IDS_REPLACE_OUTLOOK             51422
#define IDS_INPUT_OUTLOOK_NAME          51423
#define IDS_OUTLOOK_NAME_EXIST          51424
#define IDS_SEL_OUTLOOK_BEFORE_DEL      51425
#define IDS_SURE_DEL_OUTLOOK            51426
#define IDS_PPT_NOT_INSTALL             51427
#define IDS_PROFILE                     51428
#define IDS_CAPTURE_VIDEO               51429
#define IDS_CODEC_ID                    51430
#define IDS_BIT_RATE                    51431
#define IDS_SAMPLE_RATE                 51432
#define IDS_CHANNELS                    51433
#define IDS_FRAME_RATE                  51434
#define IDS_HEIGHT                      51435
#define IDS_WIDTH                       51436
#define ID_BTN_EDIT_PPT                 51437
#define ID_BTN_CHANGE_PPT               51438
#define ID_BTN_REGEN_PPT                51439
#define IDS_SURE_TO_DEL_AFTER_BKUP      51440
#define IDS_BACKINGUP_COURSE            51441
#define IDS_BACKUP_COMPLETE             51442
#define IDS_FAIL_TO_BACK_COURSE         51443
#define IDS_COURSE_EXISTS               51444
#define IDS_OPTION_TV_IMAGE             51444
#define IDS_SURE_TO_DEL_AFTER_RESTORE   51445
#define IDS_RESTORING_COURSE            51446
#define IDS_RESTORE_COMPLETE            51447
#define IDS_FAIL_TO_RESTORE_COURSE      51448
#define IDS_OPTION_SET_TIME_ACCU        51449
#define IDS_DELETE_COMPLETE             51450
#define IDS_DELETING_COURSE             51451
#define IDS_SELECT_TO_DELETE            51452
#define IDS_FAIL_TO_DEL_COURSE          51453
#define IDS_RESTORE_COURSE_FOUND        51454
#define IDS_RESTORE_COURSE_OVERWRITE    51455
#define IDS_RESTORE_COURSE_NEWNAME      51456
#define IDS_BACKUP_COURSE_FOUND         51457
#define IDS_BACKUP_COURSE_OVERWRITE     51458
#define IDS_BACKUP_COURSE_NEWNAME       51459
#define IDS_NEW_COURSE_FOUND            51460
#define IDS_NEW_COURSE_OVERWRITE        51461
#define IDS_NEW_COURSE_NEWNAME          51462
#define IDS_RESTORE_COURSE_TITLE        51463
#define IDS_BACKUP_COURSE_TITLE         51464
#define IDS_NEW_COURSE_TITLE            51465
#define IDS_DELETE_COURSE               51466
#define IDS_EXPORT_COURSE               51467
#define IDS_COURSE_NOT_GEN              51468
#define IDS_SEL_PPT_FOR_REGEN           51469
#define IDS_SEL_PPT_FOR_REPLACE         51470
#define IDS_PPT_OLE_NOT_FOUND           51471
#define IDS_DAY_LEFT                    51472
#define IDS_NOT_MARK_FOR_REPLACE        51472
#define IDS_WRONG_KEY                   51473
#define IDS_INCOMPLETE_INSTALL          51474
#define IDS_TIME_LEFT                   51475
#define IDS_INSERT_AT_TIME              51476
#define IDS_REPLACE_BETWEEN_TIME        51477
#define IDS_REG_SUCCESS                 51478
#define IDS_REG_FAIL                    51479
#define IDS_IMPORT_COMPLETE             51480
#define IDS_TIME_OUT                    51481
#define IDS_TIME_LEFT_LABEL             51482
#define IDS_EV_VERSION                  51483
#define IDS_PP_VERSION                  51483
#define IDS_ANY_DEVICE_CANNOT_EMPTY     51484
#define IDS_NO_DEVICE_AVAIL             51485
#define IDS_SET_DEVICE                  51486
#define IDS_URL                         51487
#define ID_BTN_OPEN_ASF                 51488
#define IDS_RECORDER_IS_OPENED          51489
#define IDS_FILE_NOT_INPUT              51490
#define IDS_APPEND_TO_END_OF_FILE       51491
#define IDS_OUT_OF_DATE1                51492
#define IDS_OUT_OF_DATE                 51492
#define IDS_TRIAL_VERSION               51493
#define IDS_EVAL_VERSION                51493
#define IDS_NOT_AVAILABLE_FOR_TRIAL     51494
#define IDS_DISK_FREE_LOW               51495
#define IDS_GRID_LABEL                  51496
#define IDS_DEL_AFTER_BACKUP            51497
#define ID_BTN_FIRST                    51498
#define IDS_CANNOT_CAPTURE_EXE          51499
#define IDS_CANNOT_LOAD_EXE             51500
#define IDS_BUNDLE_VERSION              51501
#define IDS_PRO_VERSION                 51502
#define IDS_CHECKOUT_URL                51503
#define IDS_IMPORT_COURSE_OVERWRITE     51504
#define IDS_IMPORT_COURSE_NEWNAME       51505
#define IDS_IMPORT_COURSE_TITLE         51506
#define IDS_IMPORTING_COURSE            51507
#define IDS_FAIL_TO_IMPORT_COURSE       51508
#define IDS_ERROR_COM_WMX_UTILITY       51509
#define IDS_SURE_DEL_PROFILE            51510
#define IDS_DRAWRECT                    52394
#define IDS_DRAWLINE                    52395
#define IDS_DRAWMARK                    52396
#define IDS_GRID_MARK_TITLE             52397
#define IDS_MARK_POINT                  52398
#define IDS_RANGE_ERROR                 52399
#define IDS_COLOR_ERROR                 52400
#define IDS_FAIL_TO_FIND_PROFILE        52401
#define IDS_NEED_CONVERT                52402
#define IDS_CONVERTING_VIDEO            52403
#define IDS_FAIL_TO_FIND_PROFILE_FILE   52404
#define IDS_FREEHAND                    52404
#define ID_BTN_BOLD                     52405
#define ID_BTN_ITALIC                   52406
#define IDS_BACKEND_VERSION             52407
#define IDS_RESOLUTION_NOT_ENOUGH       52408
#define IDS_OPTION_SHOW_ADVISOR         52409
#define IDS_OPTION_ADVISOR_TRANS        52410
#define IDS_FAIL_TO_FIND_COURSE_PROFILE 52411
#define IDS_FAIL_TO_FIND_SCREEN_PROFILE 52412
#define IDS_PPT_REPLACED                52413
#define IDS_IF_REGEN_COURSE             52414
#define IDS_CONVERT_FROM_ASF            52415
#define IDS_COURSE_NOT_GENERATED        52416
#define IDS_FAIL_TO_FIND_PPT_FILE       52417
#define IDS_KEY_EXIST                   52418
#define IDS_FAIL_TO_CONV_BY_PROFILE     52419
#define IDS_FAIL_TO_GET_PROFILE         52420
#define IDS_FAIL_TO_CAPTURE_IMAGE       52421
#define IDS_CONNECTING_SITE             52422
#define IDS_CHECK_OUT_OK                52423
#define IDS_FAIL_TO_CHECK_OUT           52424
#define IDS_FAIL_TO_FIND_TO_CHECK_OUT   52425
#define IDS_NOT_ALL_FILLED              52426
#define IDS_FAIL_TO_REGISTER            52427
#define IDS_REG_EXISTS                  52428
#define IDS_INVALID_SERIAL              52429
#define IDS_INVALID_EMAIL               52430
#define IDS_FAIL_TO_DEL_TREE            52431
#define IDS_COMPANY_URL                 52432
#define IDS_SUCCESS_REGISTER            52433
#define IDS_VERIFY_URL                  52434
#define IDS_OPTION_USE_ACTIVEX70        52435
#define IDS_BUY_QUOTA_URL               52436
#define IDS_USE_QUOTA_URL               52437
#define IDS_NOT_REGISTERED              52438
#define IDS_USE_QUOTA_OK                52439
#define IDS_FAIL_TO_FIND_QUOTA          52440
#define IDS_INVALID_SERIAL_NO           52441
#define IDS_FAIL_TO_USE_QUOTA           52442
#define IDS_GRID_BACKUP_TITLE           52443
#define IDS_DIR_ERROR                   52444
#define IDS_DEFAULT                     52445
#define IDS_BACKUP                      52446
#define IDS_NAME_DUP                    52447
#define IDS_PROMOTE_VERSION             52448
#define ID_STATIC                       55535
#define IDS_USE_DRAW_FUNCTION           59394
#define IDS_PRESENT_EMPTY               59395
#define IDS_GENETATING_COURSE           59396
#define ID_ZOOM_IN_SCALE                59397
#define ID_ZOOM_OUT_SCALE               59398
#define ID_BTN_ADD_EVENT                59399
#define ID_BTN_SAVE_VIDEO               59401
#define IDS_FAIL_TO_TAG                 59402
#define IDS_SURE_TO_MODIFY_VIDEO        59403
#define IDS_NO_MODIFY_MADE              59404
#define IDS_VIDEO_MODIFIED_SAVE         59405
#define IDS_VIDEO_MODIFIED_PREVIEW      59406
#define IDS_VIDEO                       59407
#define IDS_SYNC_POINT                  59408
#define IDS_AUDIO_REPLACE               59409
#define IDS_AUDIO_MIX                   59410
#define IDS_VIDEO_TEXT                  59411
#define IDS_VIDEO_EFFECT                59412
#define ID_BTN_ADD_WAVE                 59413
#define ID_BTN_ADD_TEXT                 59414
#define ID_BTN_ADD_EFFECT               59415
#define IDS_FAIL_TO_SAVE_VIDEO          59416
#define IDS_CONVERT_TO_WAV              59417
#define IDS_FAIL_TO_CONVERT_WAV         59418
#define IDS_FAIL_TO_CONVERT_WMA         59418
#define ID_AUDIO_REPLACE                59419
#define IDS_EFFECT_ALL_DELETED          59419
#define ID_AUDIO_MIX                    59420
#define IDS_OVERLAP_WITH_EXISTING       59420
#define ID_VIDEO_TEXT                   59421
#define IDS_CONVERT_TO_AUDIO            59421
#define ID_VIDEO_EFFECT                 59422
#define IDS_FOLDER_EMPTY                59422
#define IDS_FOLDER_NOT_EXIST            59423
#define IDS_SURE_TO_INSERT_AT_CURSOR    59424
#define IDS_FAIL_TO_CONVERT_HTM         59425
#define IDS_VIDEO_NOT_SAVED             59426
#define IDS_PROFILE_NAME                59427
#define IDS_VIDEO_AUDIO_ATTRIB          59428
#define IDS_LABEL_ATTRIB_VALUE          59429
#define IDS_MONO                        59430
#define IDS_PROFILE_NOT_INPUT           59431
#define IDS_UNTITLE                     59432
#define IDS_STEREO                      59433
#define IDS_GENERAL_PROFILE             59434
#define IDS_SCREEN_PROFILE              59435
#define IDS_PROFILE_NOT_FILLEDOUT       59436
#define IDS_SCREEN_NOT_INPUT            59437
#define IDS_CONVERTING_DEFAULT          59438
#define IDS_CONVERTING_DEMO             59439
#define IDS_CONVERTING_ASSOCIATED       59440
#define IDS_SEL_DEL_FIRST               59441
#define IDS_PROFILE_INPUT_FIRST         59442
#define IDS_SEL_RENAME_FIRST            59443
#define IDS_PROFILE_NAME_NOT_NULL       59444
#define IDS_PROFILE_NAME_EXIST          59445
#define IDS_SET_PROFILE_FIRST           59446
#define IDS_SYSTEM_DEFAULT_NOT_REN      59447
#define IDS_SYSTEM_DEFAULT_NOT_DEL      59448
#define IDS_SYSTEM_DEFAULT_NOT_ALLOWED  59449
#define IDS_DEFAULT_PROFILE_NAME        59450
#define IDS_DEFAULT_SCREEN_NAME         59451
#define ID_BTN_MUTE                     59452
#define IDS_FAIL_TO_GEN_MUTE            59453
#define ID_BTN_MUTE_FILE                59454
#define IDS_VIDEO_BANDWIDTH             59455
#define IDS_VIDEO_FPS                   59456
#define IDS_VIDEO_KEY_PER_SEC           59457
#define IDS_VIDEO_QUALITY               59458
#define IDS_AUDIO_BANDWIDTH             59459
#define IDS_AUDIO_SAMPLE_RATE           59460
#define IDS_SIZE                        59462
#define IDS_SELECT_EFFECT_FIRST         59463
#define IDS_FAIL_TO_GEN_SIDE_IMAGE      59464
#define ID_BTN_SEL_FILE                 59465
#define IDS_INPUT_VIDEO_FILE            59466
#define IDS_MEDIA_NOT_EXIST             59467
#define ID_BTN_SET_POINTS               59468
#define IDS_PPT_SYNC_WINDOW             59469
#define IDS_SET_SYNC_POINTS             59470
#define IDS_DELETE_ALL_CP               59471
#define IDS_EFFECT_CANNOT_AT_ENDS       59472
#define IDS_FAIL_TO_GEN_PROFILE         59473
#define IDS_FAIL_TO_CONVERT_TO_SAME_PROFILE 59474
#define ID_BTN_ADJUST                   59475
#define IDS_DEV_NO_VIDEO                59476
#define IDS_SEL_PRESENT                 59477
#define IDS_SEL_PPT                     59478
#define IDS_SEL_HTML                    59479
#define IDS_SEL_PPT_FIRST               59480
#define IDS_INPUT_NAME_FIRST            59481
#define IDS_INPUT_NAME                  59482
#define IDS_SEL_HTML_FIRST              59483
#define IDS_SEL_DEVICE                  59484
#define IDS_SEL_FREQ                    59485
#define IDS_SEL_LAYOUT                  59486
#define IDS_SEL_FREQ_FIRST              59487
#define IDS_NG_GENERATE                 59488
#define IDS_DEFAULT_OUTLOOK             59489
#define IDS_NG_GENERATE_CONFIRM         59490

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        257
#define _APS_NEXT_COMMAND_VALUE         32863
#define _APS_NEXT_CONTROL_VALUE         1199
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
