#define WM_USER_CAPTURE_STATUS			WM_APP+5
#define MSGPARAM_CAPTURE_TRYSTART		1
#define MSGPARAM_CAPTURE_TRYSTOP		2
#define MSGPARAM_CAPTURE_TRYPAUSE		3
#define MSGPARAM_CAPTURE_TRYRESUME		4

#define WM_USER_PROGRESS_REPORT			WM_APP+6
#define MSGTIME_PROGRESS_POSITION		1

#define WM_USER_CAPTURE_ERROR			WM_APP+10
#define MSGERROR_DEVICE_LOST			1			// DEVICE Be Removed!!
#define MSGERROR_GRAPH_ABORT			2			// Graph Abort!! (for Many Condition)

